version: '2'
services:
    master:
        image: jenkins/jenkins:lts
        container_name: jenkins
        ports:
          - 8080:8080
        volumes:
          - ./FOR_JENKINS:/var/jenkins_home
